# Generated by Django 5.0.4 on 2024-04-07 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockModel",
            fields=[
                ("stock_id", models.IntegerField(primary_key=True, serialize=False)),
                ("stock_name", models.CharField(max_length=10000000000)),
                ("stock_number", models.IntegerField()),
                ("stock_money", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
