# Generated by Django 5.0.4 on 2024-04-09 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoModel",
            fields=[
                ("crypto_id", models.IntegerField(primary_key=True, serialize=False)),
                ("crypto_name", models.CharField(max_length=10000000000)),
                ("crypto_number", models.IntegerField()),
                ("crypto_money", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
