# Generated by Django 5.0.4 on 2024-04-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_app", "0002_cryptomodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmodel",
            name="stock_pps",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="stock_money",
            field=models.FloatField(),
        ),
    ]
