# Generated by Django 5.0.4 on 2024-04-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_app", "0004_auto_20240413_0923"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmodel",
            name="stock_money",
            field=models.FloatField(default=0.0),
        ),
    ]
