# Generated by Django 5.0.4 on 2024-04-13 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fin_app", "0005_alter_stockmodel_stock_money"),
    ]

    operations = []
