# Generated by Django 5.0.4 on 2024-04-13 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fin_app", "0006_squashed_migration"),
    ]

    operations = []
