# Generated by Django 5.0.4 on 2024-04-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_app", "0007_squashed_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptomodel",
            name="crypto_ppc",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="cryptomodel",
            name="crypto_money",
            field=models.FloatField(default=0.0),
        ),
    ]
