# Generated by Django 5.0.4 on 2024-04-16 04:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fin_app", "0008_cryptomodel_crypto_ppc_and_more"),
    ]

    operations = []
