# Generated by Django 5.0.4 on 2024-04-16 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fin_app", "0010_stockmodel_close_price"),
    ]

    operations = []
