# Generated by Django 5.0.4 on 2024-04-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_app", "0011_squashed_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptomodel",
            name="close_price",
            field=models.FloatField(default=0.0),
        ),
    ]
