# Generated by Django 5.0.4 on 2024-04-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_app", "0012_cryptomodel_close_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptomodel",
            name="crypto_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stockmodel",
            name="stock_name",
            field=models.CharField(max_length=255),
        ),
    ]
