# Generated by Django 5.0.4 on 2024-04-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_app", "0015_alter_cryptomodel_crypto_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmodel",
            name="stock_number",
            field=models.IntegerField(null=True),
        ),
    ]
