# Generated by Django 5.0.4 on 2024-04-16 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fin_app", "0016_alter_stockmodel_stock_number"),
    ]

    operations = []
