# Generated by Django 5.0.4 on 2024-04-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fin_app", "0017_squashed_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptomodel",
            name="crypto_number",
            field=models.IntegerField(null=True),
        ),
    ]
